### ISSUE TITLE
Tests Hangs forever or throw unhandledpromise

### ISSUE THREAD

**Issue by gabrielruizz** [sijosyn/testcafe-browser-provider-crossbrowsertesting#3]
I've tried the plugin and although it consumes my Selenium test hours
I couldn't complete any of the tests.
I had two different situations: one is that the test hangs forever with no return, and the other is that the message below is showed:

```python
(node:18676) UnhandledPromiseRejectionWarning: Error: [init({"browserName":"Firefox","version":"25","platform":"Windows 7 64-Bit","name":"TestCafe test run DRBQMs5"})] The environment you requested was unavailable.
    at D:\CNS\TestCafe\VeloxTestCafe\node_modules\wd\lib\webdriver.js:140:15
    at Request._callback (D:\CNS\TestCafe\VeloxTestCafe\node_modules\wd\lib\http-utils.js:89:7)
    at Request.self.callback (D:\CNS\TestCafe\VeloxTestCafe\node_modules\wd\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (D:\CNS\TestCafe\VeloxTestCafe\node_modules\wd\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (D:\CNS\TestCafe\VeloxTestCafe\node_modules\wd\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
(node:18676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```
I'm using the 1.0.5 version (newest). 
Could you please help me with some information or troubleshooting?

Thanks in advance.

**Comment by gaaarg** [comment]
I had the same issue happening sometimes. And i finally identifiy when it occurs.

You had launch a test (testcafe with CBT browser) that fails but it is still running on CBT. So you need to manually stop it (or wait 5 min it autom stops). Just go to the browser interface of CrossBrowsertesting (Test Center) and stop the running test in "Automation" page.

It solve the issue for me

PS: @sijosyn thanks for you excellent work !

**Comment by sijosyn** [comment]
@gaaarg , @gabrielruizz  - Thanks for providing the workaround. I'm not using the CBT platform & this plugin anymore. So I'm not sure how to provide a fix for this solution. If you any of you know a fix for this solution, please feel free to push a change that fixes this issue.
