### ISSUE TITLE
Error on IE and Edge 

### ISSUE THREAD

**Issue by etshi** [sijosyn/testcafe-browser-provider-crossbrowsertesting#5]
I keep getting the following error when using any version of IE while the test fully pass on all other tested browsers. When testing IE manually it works normally.

```
TypeError: Unable to get property 'clientHeight' of undefined or null reference
         at h (eval code:11:10347)
         at a (http://192.168.0.34:58083/testcafe-ui.js:1:21034)
         at e (http://192.168.0.34:58083/testcafe-ui.js:1:18357)
         at o.prototype.start (http://192.168.0.34:58083/testcafe-driver.js:1:57797)
         at Anonymous function (eval code:23:5)
         at Anonymous function (eval code:13:6)
         at eval code (eval code:12:2)
         at t.prototype.iframeReadyToInitHandler (http://192.168.0.34:58083/hammerhead.js:5:4814)
         at e.prototype.emit (http://192.168.0.34:58083/hammerhead.js:10:19304)
         at t.prototype._emitEvents (http://192.168.0.34:58083/hammerhead.js:5:3511)
```
And
```
2) Unhandled promise rejection:

      { type: 'uncaughtErrorOnPage', isTestCafeError: true, callsite: CallsiteRecord { filename: '/Users/mohamedelaskalani/Documents/Projects/Cargo.one/product/client/test/E2E/main.js', lineNum: 17,
      callsiteFrameIdx: 6, stackFrames: [ [CallSite], [CallSite], [CallSite], [CallSite], [CallSite], [CallSite], [CallSite], CallSite {}, [CallSite], [CallSite], [CallSite], [CallSite], CallSite {}
      ], isV8Frames: true }, errStack: 'TypeError: Unable to get property \'clientHeight\' of undefined or null reference\n   at h (eval code:11:10347)\n   at a
      (http://192.168.0.34:58083/testcafe-ui.js:1:21034)\n   at e (http://192.168.0.34:58083/testcafe-ui.js:1:18357)\n   at o.prototype.start (http://192.168.0.34:58083/testcafe-driver.js:1:57797)\n
      at Anonymous function (eval code:23:5)\n   at Anonymous function (eval code:13:6)\n   at eval code (eval code:12:2)\n   at t.prototype.iframeReadyToInitHandler
      (http://192.168.0.34:58083/hammerhead.js:5:4814)\n   at e.prototype.emit (http://192.168.0.34:58083/hammerhead.js:10:19304)\n   at t.prototype._emitEvents
      (http://192.168.0.34:58083/hammerhead.js:5:3511)', pageDestUrl: 'https://staging.app.cargo.one/login' }

      Browser: IE 11.0.0 / Windows 7.0.0
```

**Comment by sijosyn** [comment]
@etshi The 'unhandled promise rejection' might be coming from TestCafe. You need to run tests with '-u or --skip-uncaught-errors' option? Have you tried that?

https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-u---skip-uncaught-errors
